name: Angular CI

on: 
  pull_request:
    branches:
    - dev
    - master
    
jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['22.x']

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'UI/ThriveChurchMediaToolUI/package-lock.json'

      - name: Install Dependencies
        run: |
          npm --prefix 'UI/ThriveChurchMediaToolUI' ci --legacy-peer-deps
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Verify Angular versions
        run: |
          cd UI/ThriveChurchMediaToolUI
          echo "=== Angular CLI version ==="
          npx ng version
          echo ""
          echo "=== Package versions ==="
          npm list @angular/core @angular/build @angular/cli --depth=0
          echo ""
          echo "=== Expected vs Actual ==="
          echo "Expected @angular/core: ^20.3.4"
          echo "Expected @angular/build: ^20.3.5"
          echo "Expected @angular/cli: ^20.3.5"

#      - name: Lint
#        run: |
#          npm --prefix 'UI/ThriveChurchMediaToolUI' run lint

      - name: Build
        run: |
          cd UI/ThriveChurchMediaToolUI && npx ng build
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
